sudo: false
language: node_js
node_js:
- '14'
branches:
  only:
  - master
env:
  - NODE_ENV=test
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
before_script:
- cp .env.example .env
script:
- npm test
- npm run coveralls
