version: 2.1
orbs:
  node: circleci/node@2.1.1
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn test * --coverage
      - codecov/upload:
          file: coverage/coverage-final.json
workflows:
    build-and-test:
      jobs:
        - build-and-test
